name = "trialwatch"
compatibility_date = "2024-03-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Enables Node.js compat for Edge Runtime
compatibility_flags = ["nodejs_als"]

# Production Database Binding
[[d1_databases]]
binding = "DB"
database_name = "trialwatch"
database_id = "6acd47f3-020f-4453-a5fe-13a2ca643acd"
