name = "trialwatch-app"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "trialwatch"
database_id = "6acd47f3-020f-4453-a5fe-13a2ca643acd"

